export const OH_COUNTIES = [
  "Adams",
  "Allen",
  "Ashland",
  "Ashtabula",
  "Athens",
  "Auglaize",
  "Belmont",
  "Brown",
  "Butler",
  "Carroll",
  "Champaign",
  "Clark",
  "Clermont",
  "Clinton",
  "Columbiana",
  "Coshocton",
  "Crawford",
  "Cuyahoga",
  "Darke",
  "Defiance",
  "Delaware",
  "Erie",
  "Fairfield",
  "Fayette",
  "Franklin",
  "Fulton",
  "Gallia",
  "Geauga",
  "Greene",
  "Guernsey",
  "Hamilton",
  "Hancock",
  "Hardin",
  "Harrison",
  "Henry",
  "Highland",
  "Hocking",
  "Holmes",
  "Huron",
  "Jackson",
  "Jefferson",
  "Knox",
  "Lake",
  "Lawrence",
  "Licking",
  "Logan",
  "Lorain",
  "Lucas",
  "Madison",
  "Mahoning",
  "Marion",
  "Medina",
  "Meigs",
  "Mercer",
  "Miami",
  "Monroe",
  "Montgomery",
  "Morgan",
  "Morrow",
  "Muskingum",
  "Noble",
  "Ottawa",
  "Paulding",
  "Perry",
  "Pickaway",
  "Pike",
  "Portage",
  "Preble",
  "Putnam",
  "Richland",
  "Ross",
  "Sandusky",
  "Scioto",
  "Seneca",
  "Shelby",
  "Stark",
  "Summit",
  "Trumbull",
  "Tuscarawas",
  "Union",
  "Van Wert",
  "Vinton",
  "Warren",
  "Washington",
  "Wayne",
  "Williams",
  "Wood",
  "Wyandot"
];

export function listCounties() {
  return OH_COUNTIES;
}

export function listCourts(county = "") {
  const map = {
    Wood: [
      "Wood County Court of Common Pleas",
      "Bowling Green Municipal Court",
      "Perrysburg Municipal Court"
    ],
    Franklin: [
      "Franklin County Court of Common Pleas",
      "Franklin County Municipal Court"
    ],
    Cuyahoga: [
      "Cuyahoga County Court of Common Pleas",
      "Cleveland Municipal Court"
    ]
  };

  return map[county] || [];
}
