import {defaults,courtTypes,formCategories,statuses,detectFileType,scoreCourtFormResult,buildAssetPath,buildMappingPath,detectDuplicate,normalizeState,normalizeCounty,slugify} from './court-crawler.js';
import {runJurisdictionSearch,toResult} from './jurisdiction-search.js';
const qs=(s)=>document.querySelector(s);
let existingAssets=[];let crawlResults=[];let history=JSON.parse(localStorage.getItem('jurisdictionHistory')||'[]'); let needsHumanReview=[];
const KEY='recordpathai-review-state-v2';let raw=[];const draftCache={}; const localState=JSON.parse(localStorage.getItem(KEY)||'{}');
const id=(item,i)=>`${item.sourceUrl||''}|${item.localPath||''}|${i}`; const getStatus=(item,i)=>localState[id(item,i)]?.status||item.status||'pending_review';
function saveReview(i,item,patch){localState[id(item,i)]={...(localState[id(item,i)]||{}),...patch};localStorage.setItem(KEY,JSON.stringify(localState));renderReview();}
function uniq(values){return['all',...Array.from(new Set(values.filter(Boolean))).sort()];} function sel(idv,vals){const s=document.getElementById(idv);if(s) s.innerHTML=vals.map(v=>`<option value="${v}">${v}</option>`).join('');}
function countySlug(v){const s=slugify(v);return s.endsWith('-county')?s:`${s}-county`;} function templateBase(item){return `../templates/ohio/${countySlug(item.county)}/${item.courtType}/${item.formType}`;}
async function computeMapStatus(item){if(!item.county||!item.courtType||!item.formType)return 'No mapping';const base=templateBase(item);if(draftCache[base])return draftCache[base];try{const res=await fetch(`${base}.json`,{method:'HEAD'});if(res.ok){draftCache[base]='Active';return 'Active';}}catch{} try{const d=await fetch(`${base}.draft.json`);if(!d.ok) return 'No mapping'; const b=await d.json(); return b?.status==='draft_needs_review'?'Draft mapping needs review':'Mapped';}catch{return 'No mapping';}}
function applyReviewFilters(items){const v=k=>document.getElementById(k)?.value||'all';return items.filter((x,i)=>(v('f-state')==='all'||x.state===v('f-state'))&&(v('f-county')==='all'||x.county===v('f-county'))&&(v('f-courtType')==='all'||x.courtType===v('f-courtType'))&&(v('f-status')==='all'||getStatus(x,i)===v('f-status'))&&(v('f-formType')==='all'||(x.formType||'unknown')===v('f-formType')));}
async function renderReview(){const tb=qs('#queue');if(!tb)return;tb.innerHTML='';for(const item of applyReviewFilters(raw)){const i=raw.indexOf(item);const tr=document.createElement('tr');const st=getStatus(item,i);const ms=await computeMapStatus(item);const base=templateBase(item);tr.innerHTML=`<td>${item.courtName||item.court||''}</td><td>${item.county||''}, ${item.state||''}</td><td>${item.courtType||''}</td><td>${item.formType||'unknown'}</td><td>${st}<br><small>${ms}</small></td><td>${item.score??0}<br><small>${(item.signals||[]).join(', ')}</small></td><td><a href="${item.sourcePageUrl||item.sourceUrl||'#'}" target="_blank">Open Source Page</a></td><td><button data-a='approved'>Mark Approved</button><button data-a='rejected'>Mark Rejected</button><button data-a='needs_mapping'>Mark Needs Mapping</button><button data-a='copy'>Copy Metadata JSON</button><hr><button data-a='generate_draft'>Generate Draft Mapping</button><a href="./pdf-mapper.html?draft=${encodeURIComponent(base+'.draft.json')}&final=${encodeURIComponent(base+'.json')}" target="_blank"><button type='button'>Open Draft in Mapper</button></a></td>`;tr.querySelectorAll('button').forEach(b=>b.onclick=()=>{if(b.dataset.a==='copy') return navigator.clipboard.writeText(JSON.stringify(item,null,2)); if(b.dataset.a==='generate_draft'){const cmd=`node tools/auto-map-pdf.js --county=${slugify(item.county)} --courtType=${item.courtType} --formType=${item.formType}`;navigator.clipboard.writeText(cmd);alert(cmd);return;} saveReview(i,item,{status:b.dataset.a});});tb.appendChild(tr);}}

function reliability(url){const h=(new URL(url)).hostname.toLowerCase();let s=0;if(h.endsWith('.gov'))s+=30;if(h.includes('clerk')||h.includes('court'))s+=25;return s;}
function confidence(r,p){let c=0,t=(r.title||'').toLowerCase(),u=(r.url||'').toLowerCase();if((p.courtName||'').toLowerCase()&&(`${t} ${u}`).includes((p.courtName||'').toLowerCase()))c+=25;if(r.fileType==='pdf')c+=20;if(/application|sealing|expungement|petition|record|2953/.test(`${t} ${u}`))c+=20;if((p.county||'')&&(`${t} ${u}`).includes((p.county||'').replace('-',' ')))c+=10;if((p.city||'')&&(`${t} ${u}`).includes((p.city||'').replace('-',' ')))c+=8;c+=Math.min(17,Math.floor((r.relevanceScore||0)/4));c+=Math.min(15,Math.floor(reliability(r.url)/4));return Math.max(0,Math.min(100,c));}
function rankAndTag(data,p){return data.map(r=>{const confidenceScore=confidence(r,p);const sourceReliabilityScore=reliability(r.url);let badge='Needs Review';if(confidenceScore>=90)badge='Best Match';else if(confidenceScore>=70)badge='Likely Correct Form';if(r.duplicate)badge='Duplicate';return {...r,confidenceScore,sourceReliabilityScore,badge,reviewStatus:confidenceScore<70?'needs_human_review':'candidate',draftMappingPath:`templates/${r.state}/${r.county}/${r.courtType}/${r.formCategory}.draft.json`};}).sort((a,b)=>b.confidenceScore-a.confidenceScore||b.relevanceScore-a.relevanceScore).map((r,i)=>({...r,rank:i+1}));}
const bcls=x=>x==='Best Match'?'found':x==='Likely Correct Form'?'ready':x==='Duplicate'?'duplicate':'review';
function tableRows(arr){return arr.map(r=>`<tr><td><input type='checkbox' data-id='${r.id}' ${r.confidenceScore>=90?'checked':''}></td><td>${r.rank}</td><td><span class='badge ${bcls(r.badge)}'>${r.badge}</span></td><td>${r.title||''}</td><td><a target='_blank' href='${r.url}'>Open</a></td><td>${r.fileType}</td><td>${(r.matchedKeywords||[]).join(', ')}</td><td>${r.confidenceScore}</td><td>${r.relevanceScore||0}</td><td><small>${r.localAssetPath||''}</small></td><td><small>${r.draftMappingPath}</small></td><td>${r.reviewStatus}</td><td><a class='btn ghost' target='_blank' href='./pdf-mapper.html?draft=${encodeURIComponent(r.draftMappingPath)}&final=${encodeURIComponent(r.mappingPath)}'>Open Draft in PDF Mapper</a><button class='btn ghost copy-map' data-path='${r.mappingPath}'>Copy Mapping Path</button><button class='btn ghost manual-map' data-id='${r.id}'>Mark Needs Manual Mapping</button></td></tr>`).join('');}
function download(name,obj){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(obj,null,2)],{type:'application/json'}));a.download=name;a.click();}
async function loadAssets(){try{existingAssets=await (await fetch('../data/court-assets.json')).json();}catch{existingAssets=[];}}
function createDraftMapping(r){return {version:1,status:'draft_needs_review',sourcePdfUrl:r.url,localAssetPath:r.localAssetPath,mappingPath:r.mappingPath,state:r.state,county:r.county,city:r.city||'',courtName:r.courtName||'',courtType:r.courtType,formCategory:r.formCategory,generatedAt:new Date().toISOString(),mappingMethod:'auto-draft',confidenceScore:r.confidenceScore||0,fields:[],pageMetadata:[]};}
function importSelectedFrom(scope,msg){const ids=[...document.querySelectorAll(`${scope} input:checked`)].map(x=>x.dataset.id);const selected=crawlResults.filter(x=>ids.includes(x.id));const imports=[];const drafts=[];let autoMapped=0;
for(const r of selected){const dup=detectDuplicate({sourceUrl:r.url,localAssetPath:r.localAssetPath,title:r.title,county:r.county,courtType:r.courtType,formCategory:r.formCategory},existingAssets);const rec={id:r.id,state:r.state,county:r.county,city:r.city||'',courtName:r.courtName||'',courtType:r.courtType,formCategory:r.formCategory,sourceUrl:r.url,sourceDomain:new URL(r.url).hostname,title:r.title,fileType:r.fileType,localAssetPath:r.localAssetPath,mappingPath:r.mappingPath,draftMappingPath:r.draftMappingPath,dateDiscovered:new Date().toISOString(),lastChecked:new Date().toISOString(),lastCrawledAt:new Date().toISOString(),status:dup?'duplicate':'discovered',reviewStatus:r.reviewStatus,needsMapping:true,confidenceScore:r.confidenceScore,sourceReliabilityScore:r.sourceReliabilityScore,selectionMethod:r.confidenceScore>=90?'auto':'manual',mappingMethod:r.confidenceScore>=90?'auto-draft':'manual',failureReason:'',notes:''};imports.push(rec); if(r.confidenceScore>=90){drafts.push({path:r.draftMappingPath,content:createDraftMapping(r)});autoMapped++;}}
existingAssets=[...existingAssets,...imports.filter(i=>!detectDuplicate(i,existingAssets))];download('court-assets.import.json',existingAssets);if(drafts[0]) download(`${selected[0].formCategory||'form'}.draft.json`,drafts[0].content);qs(msg).innerHTML=`<div class='msg ok'>Prepared import JSON. Draft mappings: ${autoMapped}. Place draft in templates path shown.</div>`;}
function renderJurisdiction(data){const top=data.slice(0,5), rest=data.slice(5);const host=qs('#jurisdiction-results');if(!data.length){host.innerHTML=`<div class='msg warn'>No results found. Try adding a Start URL override or lowering the search scope.</div>`;return;}host.innerHTML=`<p><button class='btn' id='bestBtn'>Select Best Match</button> <button class='btn' id='selectMapBtn'>Select Correct PDF + Create Draft Mapping</button> <button class='btn secondary' id='autoBtn'>Auto-Process High Confidence Results</button> <button class='btn secondary' id='jurImportBtn'>Import Selected Forms</button> <button class='btn ghost' id='jurExportBtn'>Export Results JSON</button> <button class='btn ghost' id='jurClearBtn'>Clear Results</button></p><h4>Top 5 Best Matches</h4><div class='table-wrap'><table><thead><tr><th></th><th>Rank</th><th>Badge</th><th>Title</th><th>Source URL</th><th>File</th><th>Keywords</th><th>Confidence</th><th>Relevance</th><th>Asset Path</th><th>Draft Path</th><th>Status</th><th>Actions</th></tr></thead><tbody id='jur-body'>${tableRows(top)}</tbody></table></div><details><summary>Review More Results (${rest.length})</summary><div class='table-wrap'><table><tbody id='jur-more'>${tableRows(rest)}</tbody></table></div></details><h4>Needs Human Review</h4><div class='table-wrap'><table><tbody>${tableRows(needsHumanReview)}</tbody></table></div>`;
qs('#bestBtn').onclick=()=>{const b=qs('#jur-body input[data-id]'); if(b) b.checked=true;};qs('#selectMapBtn').onclick=()=>importSelectedFrom('#jur-body','#j-msg');qs('#autoBtn').onclick=()=>{const hi=crawlResults.filter(r=>r.confidenceScore>=90); const lo=crawlResults.filter(r=>r.confidenceScore<90); needsHumanReview=[...needsHumanReview,...lo]; hi.forEach(r=>{const el=document.querySelector(`#jurisdiction-results input[data-id='${r.id}']`); if(el) el.checked=true; r.badge='Auto-Selected';}); importSelectedFrom('#jurisdiction-results','#j-msg'); qs('#j-msg').innerHTML+=`<div class='msg ok'>Batch summary: discovered ${crawlResults.length}, auto-selected ${hi.length}, needs review ${lo.length}.</div>`; renderJurisdiction(crawlResults);};
qs('#jurImportBtn').onclick=()=>importSelectedFrom('#jurisdiction-results','#j-msg'); qs('#jurExportBtn').onclick=()=>download('jurisdiction-results.json',{generatedAt:new Date().toISOString(),results:crawlResults,needsHumanReview}); qs('#jurClearBtn').onclick=()=>{crawlResults=[];needsHumanReview=[];host.innerHTML='';};
host.querySelectorAll('.copy-map').forEach(b=>b.onclick=()=>navigator.clipboard.writeText(b.dataset.path));host.querySelectorAll('.manual-map').forEach(b=>b.onclick=()=>{const r=crawlResults.find(x=>x.id===b.dataset.id);if(r){r.reviewStatus='needs_human_review';needsHumanReview.push(r);renderJurisdiction(crawlResults);}});
}

function renderHistory(){const tb=qs('#hist');if(!tb)return;tb.innerHTML=history.map((h,i)=>`<tr><td>${h.state}</td><td>${h.county}</td><td>${h.city}</td><td>${h.courtName}</td><td>${h.dateSearched}</td><td>${h.resultsFound}</td><td>${h.importedCount||0}</td><td><button class='btn ghost' data-i='${i}'>Re-run</button></td></tr>`).join('')||'<tr><td colspan="8">No history.</td></tr>';tb.querySelectorAll('button').forEach(b=>b.onclick=()=>{const h=history[Number(b.dataset.i)];qs('#scope').value=h.scope;qs('#j-state').value=h.state;qs('#j-county').value=h.county;qs('#j-city').value=h.city;qs('#j-court').value=h.courtName;qs('#j-ct').value=h.courtType;qs('#j-fc').value=h.formCategory;qs('#j-terms').value=h.searchTerms.join(',');});}
async function runJurisdiction(){const p={scope:qs('#scope').value,state:slugify(qs('#j-state').value),county:normalizeCounty(qs('#j-county').value),city:slugify(qs('#j-city').value),courtName:qs('#j-court').value,courtType:qs('#j-ct').value,formCategory:qs('#j-fc').value,searchTerms:qs('#j-terms').value.split(',').map(s=>s.trim()).filter(Boolean),depth:Number(qs('#j-depth').value),maxResults:Number(qs('#j-max').value||10),startUrl:qs('#j-url').value.trim()}; qs('#j-msg').innerHTML=`<div class='msg warn'>Searching…</div>`;const data=await runJurisdictionSearch(p);let base=[];
if(data.backendConfigured===false){qs('#j-msg').innerHTML=`<div class='msg warn'><strong>Search backend not configured</strong><br/>Start URL override suggestion: try your clerk/court forms page.<br/>Node fallback: <code>${data.fallbackCommand||''}</code></div>`; base=data.queries.map((q,i)=>toResult(q,p,i));}
else {base=(data.results||[]).map(r=>({...r,status:r.status||'Found',state:r.state||p.state,county:r.county||p.county,courtType:r.courtType||p.courtType,formCategory:r.formCategory||p.formCategory,fileType:r.fileType||detectFileType(r.url),localAssetPath:r.localAssetPath||buildAssetPath(p.state,p.county,p.courtType,p.formCategory,r.title||'court-form',detectFileType(r.url)),mappingPath:r.mappingPath||buildMappingPath(p.state,p.county,p.courtType,p.formCategory),city:p.city,courtName:p.courtName}));qs('#j-msg').innerHTML=`<div class='msg ok'>Found ${base.length} results from backend.</div>`;}
crawlResults=rankAndTag(base,p).slice(0,25);needsHumanReview=crawlResults.filter(r=>r.confidenceScore<70||r.badge==='Duplicate'); const hc=crawlResults.filter(r=>r.confidenceScore>=90).length;const nr=needsHumanReview.length;
const mode=data.backendConfigured===false?'Manual fallback':(data.knownJurisdictionShortcutUsed?'Known shortcut':(data.ddgFallbackActive?'DDG fallback':'Live backend'));
qs('#jurisdiction-status').innerHTML=`<div class='status-panel'><div><strong>Backend:</strong> ${data.backendConfigured?'Active':'Not Configured'}</div><div><strong>Results found:</strong> ${crawlResults.length}</div><div><strong>Search mode:</strong> ${mode}</div><div><strong>High-confidence:</strong> ${hc}</div><div><strong>Needs-review:</strong> ${nr}</div><div><strong>Errors:</strong> ${(data.errors||[]).join(' | ')||'None'}</div></div>`;
renderJurisdiction(crawlResults);history.unshift({...p,dateSearched:new Date().toISOString(),resultsFound:crawlResults.length,importedCount:0});history=history.slice(0,20);localStorage.setItem('jurisdictionHistory',JSON.stringify(history));renderHistory();}
function mountCrawlUI(el){el.innerHTML=`<h2>Court Website Crawler</h2><div id='crawl-msg'></div><div class='grid'><div><label>URL</label><input id='url'></div><div><label>State</label><input id='state' value='ohio'></div><div><label>County</label><input id='county' value='wood-county'></div><div><label>Court type</label><select id='courtType'>${courtTypes.map(x=>`<option>${x}</option>`)}</select></div><div><label>Form category</label><select id='formCategory'>${formCategories.map(x=>`<option>${x}</option>`)}</select></div><div class='full'><label>Keywords</label><input id='keywords' value='${defaults.keywords}'></div><div><label>Depth</label><select id='depth'><option>1</option><option selected>2</option><option>3</option></select></div><div><label>Allow external links <input type='checkbox' id='allowExt'></label></div></div><p><button class='btn' id='crawlBtn'>Crawl Court Site</button> <button class='btn secondary' id='importBtn'>Import Selected Forms</button> <button class='btn ghost' id='exportBtn'>Export Results JSON</button></p><div class='table-wrap'><table><thead><tr><th></th><th>Title</th><th>URL</th><th>Type</th><th>Keywords</th><th>Score</th><th>State</th><th>County</th><th>Court</th><th>Category</th><th>Asset Path</th><th>Status</th></tr></thead><tbody id='crawl-body'></tbody></table></div>`;qs('#crawlBtn').onclick=async()=>{};qs('#importBtn').onclick=()=>importSelectedFrom('#crawl-body','#crawl-msg');qs('#exportBtn').onclick=()=>download('crawler-results.json',{generatedAt:new Date().toISOString(),results:crawlResults,statuses});}
function mountJurisdictionUI(el){el.innerHTML=`<h2>Jurisdiction Search</h2><div class='grid'><div><label>Scope</label><select id='scope'><option>statewide</option><option selected>county</option><option>city</option><option>court</option></select></div><div><label>State</label><input id='j-state' value='ohio'></div><div><label>County</label><input id='j-county' value='wood-county'></div><div><label>City</label><input id='j-city' value='bowling-green'></div><div><label>Court name</label><input id='j-court' value='Wood County Municipal Court'></div><div><label>Court type</label><select id='j-ct'>${courtTypes.map(x=>`<option>${x}</option>`)}</select></div><div class='full'><label>Terms</label><input id='j-terms' value='sealing,expungement,record sealing,application'></div><div><label>Form category</label><select id='j-fc'>${formCategories.map(x=>`<option>${x}</option>`)}</select></div><div><label>Depth</label><select id='j-depth'><option>1</option><option selected>2</option><option>3</option></select></div><div><label>Max results</label><input id='j-max' type='number' value='10'></div><div class='full'><label>Start URL override</label><input id='j-url'></div></div><p><button class='btn' id='runJ'>Run Jurisdiction Search</button></p><div id='j-msg'></div><div id='jurisdiction-status'></div><div id='jurisdiction-results'></div><h3>Saved Search History</h3><div class='table-wrap'><table><thead><tr><th>State</th><th>County</th><th>City</th><th>Court</th><th>Date</th><th>Found</th><th>Imported</th><th>Re-run</th></tr></thead><tbody id='hist'></tbody></table></div>`;qs('#runJ').onclick=runJurisdiction;renderHistory();}
export async function initAssetManager(){raw=await (await fetch('./review-queue.json',{cache:'no-store'})).json();sel('f-state',uniq(raw.map(x=>x.state)));sel('f-county',uniq(raw.map(x=>x.county)));sel('f-courtType',uniq(raw.map(x=>x.courtType)));sel('f-status',uniq(raw.map((x,i)=>getStatus(x,i))));sel('f-formType',uniq(raw.map(x=>x.formType||'unknown')));document.querySelectorAll('#tab-review select').forEach(s=>s.onchange=renderReview);await renderReview();await loadAssets();mountCrawlUI(qs('#tab-crawler'));mountJurisdictionUI(qs('#tab-jurisdiction'));document.querySelectorAll('.tab-btn').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab-btn').forEach(x=>x.classList.remove('active'));b.classList.add('active');['review','crawler','jurisdiction'].forEach(t=>qs(`#tab-${t}`).classList.add('hide'));qs(`#tab-${b.dataset.tab}`).classList.remove('hide');});}
if(qs('#tab-review')) initAssetManager(); export function initCrawlerStandalone(){mountCrawlUI(qs('#tab-crawler'));loadAssets();}
