#!/usr/bin/env node
import fs from 'node:fs/promises';
import path from 'node:path';

const ROOT = process.cwd();
const REQUIRED_FIELDS = [
  ['court.case_number', ['case no', 'case number']],
  ['court.judge_name', ['judge']],
  ['petitioner.full_name', ['name', 'applicant']],
  ['petitioner.address.line1', ['address']],
  ['petitioner.address.line2', ['city/state/zip', 'city state zip']],
  ['petitioner.address.city', ['city']],
  ['petitioner.address.state', ['state']],
  ['petitioner.address.zip', ['zip']],
  ['petitioner.phone', ['phone']],
  ['petitioner.email', ['email']],
  ['generated.current_date', ['date']],
  ['charges.0.charge_name', ['charge', 'offense']],
  ['charges.0.charge_code', ['offense code', 'code']],
  ['charges.0.level', ['degree']],
  ['charges.0.disposition_date', ['disposition date']],
  ['charges.0.probation_end_date', ['date']],
  ['petitioner.signature', ['signature']]
];

const args = Object.fromEntries(process.argv.slice(2).map((x)=>{const [k,v]=x.replace(/^--/,'').split('='); return [k,v];}));
const county = args.county || 'wood';
const courtType = args.courtType || 'court-of-common-pleas';
const formType = args.formType || 'sealing-conviction';

function slugCounty(value){const slug=value.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,''); return slug.endsWith('-county')?slug:`${slug}-county`;}
function norm(s){return String(s||'').toLowerCase().replace(/[^a-z0-9]/g,'');}

async function getPdfDocumentLoader() {
  try {
    const module = await import('pdfjs-dist/legacy/build/pdf.mjs');
    return module.getDocument;
  } catch (error) {
    if (error && (error.code === 'ERR_MODULE_NOT_FOUND' || String(error.message || '').includes('pdfjs-dist'))) {
      console.error('Missing pdfjs-dist. Run npm install pdfjs-dist.');
      process.exit(1);
    }
    throw error;
  }
}

async function extractTextItems(pdfPath){
  const getDocument = await getPdfDocumentLoader();
  const data = new Uint8Array(await fs.readFile(pdfPath));
  const loadingTask = getDocument({ data, useSystemFonts: true });
  const pdf = await loadingTask.promise;
  const all = [];
  for(let p=1;p<=pdf.numPages;p++){
    const page = await pdf.getPage(p);
    const content = await page.getTextContent();
    for (const item of content.items) {
      const [,, , ,x,y] = item.transform;
      all.push({ text: item.str, x, y, width: item.width || 140, height: item.height || 20, page: p });
    }
  }
  return { items: all, pageCount: pdf.numPages };
}

function findBest(items, labels){
  const labelNorm = labels.map(norm);
  const matches = items.filter(i => labelNorm.some(l=>norm(i.text).includes(l)));
  matches.sort((a,b)=>b.text.length-a.text.length);
  return matches[0] || null;
}

function mappingFromLabel(name, label, id){
  const x = Math.min(label.x + Math.max(label.width, 90) + 8, 560);
  const y = label.y - 10;
  const isDate = name.includes('date');
  const confidence = Math.max(0.35, Math.min(0.95, (label.text.length/20)));
  return { id, name, type: isDate ? 'date' : 'text', page: label.page, x: Math.round(x), y: Math.round(y), width: name.includes('charge')?160:180, height: 24, autoGenerated: true, needsReview: true, confidence: Number(confidence.toFixed(2)) };
}

(async()=>{
  const inputPdf = path.join(ROOT,'assets','forms','ohio',county,courtType,`${formType}.pdf`);
  const countySlug = slugCounty(county);
  const outputPath = path.join(ROOT,'templates','ohio',countySlug,courtType,`${formType}.draft.json`);
  const { items, pageCount } = await extractTextItems(inputPdf);
  const mappings = [];
  let id=1;
  for (const [name, labels] of REQUIRED_FIELDS){
    const label = findBest(items, labels) || items[0];
    mappings.push(mappingFromLabel(name,label,id++));
  }
  const payload = { version: 1, exportedAt: new Date().toISOString(), document: path.basename(inputPdf), pageCount, status: 'draft_needs_review', autoGenerated: true, mappings };
  await fs.mkdir(path.dirname(outputPath), { recursive: true });
  await fs.writeFile(outputPath, JSON.stringify(payload,null,2));
  console.log(`Draft mapping written: ${path.relative(ROOT, outputPath)}`);
})();
